=== VISTALL/jn/jn/resource/protocols/protocol.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT protocol (macro|packetfamilly|global_listeners|session_listeners)*>
<!ATTLIST protocol
	crypt CDATA #REQUIRED
	order CDATA #IMPLIED
	name CDATA #REQUIRED
	extends CDATA #IMPLIED>
<!ELEMENT macro (part|for)*>
<!ATTLIST macro
	id CDATA #REQUIRED
	name CDATA #IMPLIED>
<!ELEMENT part (reader)*>
<!ATTLIST part
	id CDATA #IMPLIED
	name CDATA #REQUIRED
	size CDATA #IMPLIED
	type CDATA #REQUIRED
	val CDATA #IMPLIED>
<!ELEMENT packetfamilly (packet)*>
<!ATTLIST packetfamilly
	way CDATA #REQUIRED>
<!ELEMENT packet (part|for|switch|macro|changeOrder|if)*>
<!ATTLIST packet
	id CDATA #REQUIRED
	key CDATA #IMPLIED
	server_list CDATA #IMPLIED
	extended CDATA #IMPLIED
	name CDATA #REQUIRED>
<!ELEMENT for (part|macro|switch|for|if)*>
<!ATTLIST for
	id CDATA #IMPLIED
	fixed CDATA #IMPLIED
	name CDATA #IMPLIED>
<!ELEMENT if (part|macro|switch|for|if)*>
<!ATTLIST if
	field CDATA #REQUIRED
	operator CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT switch (case)*>
<!ELEMENT changeOrder (#PCDATA)>
<!ATTLIST changeOrder
	order CDATA #REQUIRED>
<!ATTLIST switch
	id CDATA #REQUIRED>
<!ELEMENT case (part|for|macro)*>
<!ATTLIST case
	id CDATA #REQUIRED
	name CDATA #IMPLIED>
<!ELEMENT reader (#PCDATA)>
<!ATTLIST reader
	type CDATA #REQUIRED>

<!ELEMENT global_listeners (listener)*>
<!ELEMENT session_listeners (listener)*>

<!ELEMENT listener (#PCDATA)>
<!ATTLIST listener
	name CDATA #REQUIRED>

=== VISTALL/jn/jn/resource/protocols/Unity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE protocol SYSTEM "protocol.dtd">
<protocol name="Unity" crypt="Null" order="BIG_ENDIAN">
	<packetfamilly way="CLIENT">
		<packet id="00" name="Any">
			<part name="metadataSize" type="d" />
			<part name="fileSize" type="ud" />
			<part name="versionInfo" type="d" />
			<part name="dataOffset" type="ud" />
			<part name="endianness" type="c" />
			<part name="reserved1" type="c" />
			<part name="reserved2" type="c" />
			<part name="reserved3" type="c" />
		</packet>
	</packetfamilly>

	<packetfamilly way="SERVER">

	</packetfamilly>
</protocol>
